origTeamNames = [
"Brigham Young",
"Bowling",
"Central M",
"Central F",
"UConn",
"Atlantic",
"Florida I",
"Ga. Southern",
"Ga. Tech",
"GA Southern",
"GA Tech",
"Lafayette",
"Monroe",
"LA Tech",
"La. Tech",
"Middle T",
"Mass",
"Ole Miss",
"Mississippi State",
"N Carolina",
"N. Carolina",
"Northern I",
"N Ill",
"Carolina St",
"N Mex",
"Mexico State",
"N. Texas",
"ODU",
"South Ala",
"South Carolina",
"S Florida",
"South Florida",
"S Miss",
"Texas Christ",
"El Paso",
"TX-San",
"Virginia Tech",
"West Virginia",
"W Ken",
"Western Ken",
"W Mich",
"Western Mich",
"Washington S",
]
newTeamNames = [
"BYU",
"BGSU",
"CMU",
"UCF",
"Connecticut",
"FAU",
"FIU",
"Georgia Southern",
"Georgia Tech",
"Georgia Southern",
"Georgia Tech",
"Louisiana",
"Monroe",
"Louisiana Tech",
"Louisiana Tech",
"MTSU",
"Umass",
"Mississippi",
"Miss State",
"North Carolina",
"North Carolina",
"NIU",
"NIU",
"NC State",
"NMSU",
"NMSU",
"North Texas",
"Old Dominion",
"S Alabama",
"S Carolina",
"USF",
"USF",
"Southern Mississippi",
"TCU",
"UTEP",
"UTSA",
"VA Tech",
"W Virginia",
"WKU",
"WKU",
"WMU",
"WMU",
"Wash State",
]

acceptedTeamNames = [ #format: string, int, boolean: team name, index corresponding to team, if "State" is added after the name
    ["Air Force", 0, False],
    ["Akron", 1, False],
    ["Alabama", 2, False],
    ["Appalachian", 3, True],
    ["App", 3, True],
    ["App.", 3],
    ["Arizona", 4, False],
    ["Arizona", 5, True],
    ["Arkansas", 6, False],
    ["Arkansas", 7, True],
    ["Army", 8, False],
    ["West Point", 8, False],
    ["Auburn", 9, False],
    ["Bowling Green", 10, True],
    ["BGSU", 10, False],
    ["BYU", 11, False],
    ["Brigham Young", 11, False],
    ["Ball", 12, True],
    ["Baylor", 13, False],
    ["Boise", 14, True],
    ["Boston College", 15, False],
    ["Boston", 15, False],
    ["Buffalo", 16, False],
    ["Central Michigan", 17, False],
    ["CMU", 17, False],
    ["California", 18, False],
    ["Cal", 18, False],
    ["Berkeley", 18, False],
    ["UC-Berkeley", 18, False],
    ["UC Berkeley", 18, False],
    ["Charlotte", 19, False],
    ["UNC Charlotte", 19, False],
    ["UNC-Charlotte", 19, False],
    ["Cincinnati", 20, False],
    ["Clemson", 21, False],
    ["Coastal Carolina", 22, False],
    ["Coastal", 22, False],
    ["CCU", 22, False],
    ["Colorado", 23, False],
    ["Colorado Boulder", 23, False],
    ["CU Boulder", 23, False],
    ["Colorado", 24, True],
    ["CSU", 24, False],
    ["Connecticut", 25, False],
    ["UConn", 25, False],
    ["Uconn", 25, False],
    ["Duke", 26, False],
    ["East Carolina", 27, False],
    ["Eastern Carolina", 27, False],
    ["ECU", 27, False],
    ["Eastern Michigan", 28, False],
    ["EMU", 28, False],
    ["East Michigan", 28, False],
    ["FAU", 29, False],
    ["Florida Atlantic", 29, False],
    ["FIU", 30, False],
    ["Florida International", 30, False],
    ["Florida", 31, False],
    ["UF", 31, False],
    ["Florida", 32, True],
    ["FSU", 32, False],
    ["Fresno", 33, True],
    ["Georgia", 34, False],
    ["UGA", 34, False],
    ["Georgia Southern", 35, False],
    ["Georgia", 36, True],
    ["Georgia Tech", 37, False],
    ["Hawaii", 38, False],
    ["Houston", 39, False],
    ["UH", 39, False],
    ["Illinois", 40, False],
    ["Indiana", 41, False],
    ["Iowa", 42, False],
    ["Iowa", 43, True],
    ["Kansas", 44, False],
    ["KU", 44, False],
    ["Kansas", 45, True],
    ["KSU", 45, False],
    ["Kent", 46, True],
    ["Kentucky", 47, False],
    ["UK", 47, False],
    ["LSU", 48, False],
    ["Louisiana", 48, True],
    ["Liberty", 49, False],
    ["Louisiana", 50, False],
    ["Lafayette", 50, False],
    ["UL Lafayette", 50, False],
    ["UL-Lafayette", 50, False],
    ["Louisiana Lafayette", 50, False],
    ["Louisiana at Lafayette", 50, False],
    ["Louisiana Tech", 51, False],
    ["LA Tech", 51, False],
    ["Louisville", 52, False],
    ["Middle Tennessee", 53, True],
    ["MTSU", 53, False],
    ["Marshall", 54, False],
    ["Maryland", 55, False],
    ["Memphis", 56, False],
    ["Miami", 57, False],
    ["Miami-OH", 58, False],
    ["Miami OH", 58, False],
    ["Miami Ohio", 58, False],
    ["Miami-Ohio", 58, False],
    ["Miami of Ohio", 58, False],
    ["Michigan", 59, False],
    ["Michigan", 60, True],
    ["Minnesota", 61, False],
    ["Mississippi", 62, True],
    ["Miss", 62, True],
    ["Miss.", 62, True],
    ["Ole Miss", 63, False],
    ["Mississippi", 63, False],
    ["Miss", 63, False],
    ["Missouri", 64, False],
    ["Mizzou", 64, False],
    ["UL-Monroe", 65, False],
    ["UL Monroe", 65, False],
    ["Monroe", 65, False],
    ["Louisiana Monroe", 65, False],
    ["Louisiana at Monroe", 65, False],
    ["NC", 66, True],
    ["NC.", 66, True],
    ["North Carolina", 66, True],
    ["Northern Illinois", 67, False],
    ["NIU", 67, False],
    ["North Illinois", 67, False],
    ["New Mexico", 68, True],
    ["NMSU", 68, False],
    ["Navy", 69, False],
    ["Nebraska", 70, False],
    ["Nevada", 71, False],
    ["New Mexico", 72, False],
    ["North Carolina", 73, False],
    ["UNC", 73, False],
    ["UNC-Chapel Hill", 73, False],
    ["UNC Chapel Hill", 73, False],
    ["North Texas", 74, False],
    ["Northwestern", 75, False],
    ["Notre Dame", 76, False],
    ["ND", 76, False],
    ["Ohio", 77, False],
    ["Ohio", 78, True],
    ["Oklahoma", 79, True],
    ["OK", 79, True],
    ["Oklahoma", 80, False],
    ["OK", 80, False],
    ["Old Dominion", 81, False],
    ["ODU", 81, False],
    ["Oregon", 82, False],
    ["Oregon", 83, True],
    ["Penn", 84, True],
    ["Pennsylvania", 84, True],
    ["PSU", 84, False],
    ["Pittsburgh", 85, False],
    ["Pitt", 85, False],
    ["Purdue", 86, False],
    ["Rice", 87, False],
    ["Rutgers", 88, False],
    ["South Alabama", 89, False],
    ["Southern Alabama", 89, False],
    ["South Carolina", 90, False],
    ["SCAR", 90, False],
    ["SMU", 91, False],
    ["Southern Methodist", 91, False],
    ["San Diego", 92, True],
    ["SDSU", 92, False],
    ["San Jose", 93, True],
    ["SJSU", 93, False],
    ["Soutern Mississippi", 94, False],
    ["Southern Miss", 94, False],
    ["USM", 94, False],
    ["Stanford", 95, False],
    ["Syracuse", 96, False],
    ["TCU", 97, False],
    ["Texas Christian", 97, False],
    ["Temple", 98, False],
    ["Tennessee", 99, False],
    ["Texas", 100, False],
    ["UT Austin", 100, False],
    ["UT-Austin", 100, False],
    ["Texas Austin", 100, False],
    ["Texas at Austin", 100, False],
    ["Texas A&M", 101, False],
    ["A&M", 101, False],
    ["TAMU", 101, False],
    ["Texas", 102, True],
    ["Texas Tech", 103, False],
    ["TTU", 103, False],
    ["Toledo", 104, False],
    ["Troy", 105, False],
    ["Tulane", 106, False],
    ["Tulsa", 107, False],
    ["UAB", 108, False],
    ["Alabama Birmingham", 108, False],
    ["Alabama at Birmingham", 108, False],
    ["UCF", 109, False],
    ["Central Florida", 109, False],
    ["UCLA", 110, False],
    ["California Los Angeles", 110, False],
    ["California at Los Angeles", 110, False],
    ["UNLV", 111, False],
    ["Nevada Las Vegas", 111, False],
    ["Nevada at Las Vegas", 111, False],
    ["USC", 112, False],
    ["South California", 112, False],
    ["Southern California", 112, False],
    ["USF", 113, False],
    ["South Florida", 113, False],
    ["UTEP", 114, False],
    ["Texas El Paso", 114, False],
    ["Texas El-Paso", 114, False],
    ["Texas at El Paso", 114, False],
    ["Texas at El Paso", 114, False],
    ["El Paso", 114, False],
    ["El-Paso", 114, False],
    ["UTSA", 115, False],
    ["Texas San Antonio", 115, False],
    ["Texas at San Antonio", 115, False],
    ["San Antonio", 115, False],
    ["Massachussetts", 116, False],
    ["UMass", 116, False],
    ["Umass", 116, False],
    ["Utah", 117, False],
    ["Utah", 118, True],
    ["USU", 118, False],
    ["Virginia Tech", 119, False],
    ["VT", 119, False],
    ["Vanderbilt", 120, False],
    ["Virginia", 121, False],
    ["UVA", 121, False],
    ["West Virginia", 122, False],
    ["WVU", 122, False],
    ["Western Kentucky", 123, False],
    ["WKU", 123, False],
    ["West Kentucky", 123, False],
    ["Western Michigan", 124, False],
    ["WMU", 124, False],
    ["West Michigan", 124, False],
    ["Wake Forest", 125, False],
    ["WFU", 125, False],
    ["Washington", 126, True],
    ["WSU", 126, False],
    ["Wash", 126, True],
    ["Washington", 127, False],
    ["Wash", 127, False],
    ["UWash", 127, False],
    ["Wisconsin", 128, False],
    ["Wyoming", 129, False],
]